export enum EmitterEnum {
  ShowModal = 'showModal',
  SelectCar = 'selectCar',
  ChangeLogo = 'changeLogo',
  UpdateCars = 'updateCars',
  AppendWinner = 'appendWinner',
  GenerateWinners = 'generateWinners',
  UpdateWinnersLogo = 'updateWinnersLogo',
  ChangeNumberGaragePage = 'changeNumberGaragePage',
  ChangeNumberWinnersPage = 'changeNumberWinnersPage',
  LockGaragePaginationButtons = 'lockGaragePaginationButtons',
  UnlockGaragePaginationButtons = 'unlockGaragePaginationButtons',
  LockWinnersPaginationButtons = 'lockWinnersPaginationButtons',
  UnlockWinnersPaginationButtons = 'unlockWinnersPaginationButtons',
}
