export enum EmitterEnum {
  changeLogo = 'changeLogo',
  changeElementsOnState = 'changeElementsOnState',
  resetLevels = 'resetLevels',
  setupWin = 'setupWin',
  setupHelp = 'setupHelp',
  showModal = 'showModal',
  setToLastTask = 'setToLastTask',
  updateCars = 'updateCars',
  updatePaginationCars = 'updatePaginationCars',
  changeNumberPage = 'changeNumberPage',
  selectCar = 'selectCar',
  startRace = 'startRace',
  lockGaragePaginationButtons = 'lockGaragePaginationButtons',
  unlockGaragePaginationButtons = 'unlockGaragePaginationButtons',
}
